baseURL = "https://npu-wsr.github.io"
title = "Hawking: a wheeled soccer robot"
theme = "sourgough-starter"
publishDir = "docs"
relativeURLs = true

[markup.goldmark.renderer]
    unsafe= true

[params]
#------------- Config -------------------
    scholarLink = false
    scopusLink = false
    dimensionsLink = false
    dimensionCitations = false
    backgroundPath = "images/SA_back.png"
    googleScholar = 'XXXX' # These are needed only if set to true above
    scopusID = 'XXXX'
    dimensionsID = 'XXXX'
    footerOffset = -60

#-------------- Defined ------------
    css= ["css/sourgough.css"]

[menu]
#----- Navbar links ------
  [[menu.main]]
    identifier = "docs"
    name = "Docs"
    url = "/docs/"

  [[menu.main]]
    identifier = "album"
    name = "Album"
    url = "/album/"

  [[menu.main]]
    identifier = "people"
    name = "People"
    url = "/people/"

#----- NavBottom Links ------
  [[menu.bot]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/npu-wsr"
    pre = "fab fa-github"

#----------- Text Links -------
  [[menu.link]]
    identifier = "university"
    name = "Northwestern Polytechnical University, Shaanxi Xi'an"
    url = "https://www.nwpu.edu.cn"

[taxonomies]
  authors = "authors"
