baseURL = "https://npu-wsr.github.io/soccer_robot_site/"
title = "Hawking: a wheeled soccer robot"
theme = "sourgough-starter"
publishDir = "docs"
relativeURLs = true

[markup.goldmark.renderer]
    unsafe= true

[params]
#------------- Config -------------------
    scholarLink = true
    scopusLink = true
    dimensionsLink = true
    dimensionCitations = true
    backgroundPath = "images/SA_back.png"
    googleScholar = 'XXXX' # These are needed only if set to true above
    scopusID = 'XXXX'
    dimensionsID = 'XXXX'
    footerOffset = -60

#-------------- Defined ------------
    css= ["css/sourgough.css"]

[menu]
#----- Navbar links ------
  [[menu.main]]
    identifier = "docs"
    name = "Docs"
    url = "/docs/"

  [[menu.main]]
    identifier = "album"
    name = "Album"
    url = "/album/"

  [[menu.main]]
    identifier = "people"
    name = "People"
    url = "/people/"

#----- NavBottom Links ------
  [[menu.bot]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/jack-alope/"
    pre = "fab fa-github"

  [[menu.bot]]
    identifier = "gitlab"
    name = "Gitlab"
    url = "https://gitlab.com/jack-alope/"
    pre = "fab fa-gitlab"

  [[menu.bot]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/jackmurphyf/"
    pre = "fab fa-linkedin-in"

  

#-------- About section links ----- 
  [[menu.about]]
    identifier = "ordcidid"
    name = "OrcidID"
    url = ""
    pre = "fab fa-orcid"

  [[menu.about]]
    identifier = "researchgate"
    name = "ResearchGate"
    url = ""
    pre = "fab fa-researchgate"

  [[menu.about]]
    identifier = "medium"
    name = "Medium"
    url = ""
    pre = "fab fa-medium-m"

  [[menu.about]]
    identifier = "googlescholar"
    name = "Google Scholar"
    url = ""
    pre = "fas fa-graduation-cap"

#----------- Text Links -------
  [[menu.link]]
    identifier = "email"
    name = "email@example.com"
    url = "mailto:email@example.com"

  [[menu.link]]
    identifier = "resume"
    name = "resume"
    url = ""

[taxonomies]
  authors = "authors"
